/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvanceRequest {
  'status' : string,
  'total_repaid' : number,
  'approved_date' : [] | [string],
  'emp_id' : bigint,
  'advance_id' : bigint,
  'repayment_months' : bigint,
  'amount' : number,
  'reason' : string,
  'monthly_deduction' : number,
  'request_date' : string,
}
export interface AdvanceRequestWithName {
  'status' : string,
  'emp_name' : string,
  'total_repaid' : number,
  'approved_date' : [] | [string],
  'emp_id' : bigint,
  'advance_id' : bigint,
  'repayment_months' : bigint,
  'amount' : number,
  'reason' : string,
  'monthly_deduction' : number,
  'request_date' : string,
}
export interface Attendance {
  'status' : string,
  'date' : string,
  'emp_id' : bigint,
  'overtime_hours' : number,
  'attendance_id' : bigint,
  'check_out' : [] | [string],
  'check_in' : [] | [string],
  'total_hours' : number,
}
export interface AttendanceRecord {
  'status' : string,
  'emp_name' : string,
  'date' : string,
  'emp_id' : bigint,
  'overtime_hours' : number,
  'attendance_id' : bigint,
  'check_out' : [] | [string],
  'check_in' : [] | [string],
  'total_hours' : number,
}
export interface Employee {
  'emp_code' : string,
  'status' : string,
  'base_salary' : number,
  'joining_date' : string,
  'name' : string,
  'designation' : string,
  'emp_id' : bigint,
  'department' : string,
  'biometric_id' : string,
}
export interface NewEmployee {
  'emp_code' : string,
  'base_salary' : number,
  'joining_date' : string,
  'name' : string,
  'designation' : string,
  'department' : string,
  'biometric_id' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_2 = { 'ok' : string } |
  { 'err' : string };
export type Result_3 = { 'ok' : SalaryCalculation } |
  { 'err' : string };
export interface SalaryCalculation {
  'emp_name' : string,
  'overtime_amount' : number,
  'base_salary' : number,
  'days_in_month' : bigint,
  'net_salary' : number,
  'total_overtime_hours' : number,
  'month_year' : string,
  'emp_id' : bigint,
  'present_days' : bigint,
  'advance_deduction' : number,
  'absent_days' : bigint,
  'basic_earned' : number,
}
export interface SalaryInput {
  'overtime_amount' : number,
  'net_salary' : number,
  'month_year' : string,
  'emp_id' : bigint,
  'present_days' : bigint,
  'advance_deduction' : number,
  'absent_days' : bigint,
  'basic_earned' : number,
}
export interface SalaryRecord {
  'overtime_amount' : number,
  'processed_date' : string,
  'net_salary' : number,
  'month_year' : string,
  'emp_id' : bigint,
  'present_days' : bigint,
  'salary_id' : bigint,
  'advance_deduction' : number,
  'absent_days' : bigint,
  'basic_earned' : number,
}
export interface UpdateEmployee {
  'emp_code' : string,
  'base_salary' : number,
  'joining_date' : string,
  'name' : string,
  'designation' : string,
  'department' : string,
  'biometric_id' : string,
}
export interface _SERVICE {
  'addEmployee' : ActorMethod<[NewEmployee], Result_1>,
  'approveAdvance' : ActorMethod<[bigint, string], Result>,
  'calculateSalary' : ActorMethod<[bigint, string, string], Result_3>,
  'deleteEmployee' : ActorMethod<[bigint], Result>,
  'getAdvanceRequests' : ActorMethod<[], Array<AdvanceRequestWithName>>,
  'getAdvanceRequestsByEmployee' : ActorMethod<[bigint], Array<AdvanceRequest>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAttendance' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<AttendanceRecord>
  >,
  'getAttendanceByEmployee' : ActorMethod<
    [bigint, string, string],
    Array<Attendance>
  >,
  'getEmployee' : ActorMethod<[bigint], [] | [Employee]>,
  'getEmployeeByBiometricId' : ActorMethod<[string], [] | [Employee]>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getSalaryRecord' : ActorMethod<[bigint, string], [] | [SalaryRecord]>,
  'getSalaryRecords' : ActorMethod<[], Array<SalaryRecord>>,
  'getTotalAdvanceDeduction' : ActorMethod<[bigint, string, string], number>,
  'markAttendance' : ActorMethod<[bigint, string, string, string], Result>,
  'processBiometricScan' : ActorMethod<[string, string], Result_2>,
  'processSalary' : ActorMethod<[SalaryInput], Result_1>,
  'rejectAdvance' : ActorMethod<[bigint], Result>,
  'submitAdvanceRequest' : ActorMethod<
    [bigint, number, bigint, string],
    Result_1
  >,
  'updateEmployee' : ActorMethod<[bigint, UpdateEmployee], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];