/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewEmployee = IDL.Record({
  'emp_code' : IDL.Text,
  'base_salary' : IDL.Float64,
  'joining_date' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'department' : IDL.Text,
  'biometric_id' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const SalaryCalculation = IDL.Record({
  'emp_name' : IDL.Text,
  'overtime_amount' : IDL.Float64,
  'base_salary' : IDL.Float64,
  'days_in_month' : IDL.Int,
  'net_salary' : IDL.Float64,
  'total_overtime_hours' : IDL.Float64,
  'month_year' : IDL.Text,
  'emp_id' : IDL.Nat,
  'present_days' : IDL.Int,
  'advance_deduction' : IDL.Float64,
  'absent_days' : IDL.Int,
  'basic_earned' : IDL.Float64,
});
export const Result_3 = IDL.Variant({
  'ok' : SalaryCalculation,
  'err' : IDL.Text,
});
export const AdvanceRequestWithName = IDL.Record({
  'status' : IDL.Text,
  'emp_name' : IDL.Text,
  'total_repaid' : IDL.Float64,
  'approved_date' : IDL.Opt(IDL.Text),
  'emp_id' : IDL.Nat,
  'advance_id' : IDL.Nat,
  'repayment_months' : IDL.Int,
  'amount' : IDL.Float64,
  'reason' : IDL.Text,
  'monthly_deduction' : IDL.Float64,
  'request_date' : IDL.Text,
});
export const AdvanceRequest = IDL.Record({
  'status' : IDL.Text,
  'total_repaid' : IDL.Float64,
  'approved_date' : IDL.Opt(IDL.Text),
  'emp_id' : IDL.Nat,
  'advance_id' : IDL.Nat,
  'repayment_months' : IDL.Int,
  'amount' : IDL.Float64,
  'reason' : IDL.Text,
  'monthly_deduction' : IDL.Float64,
  'request_date' : IDL.Text,
});
export const Employee = IDL.Record({
  'emp_code' : IDL.Text,
  'status' : IDL.Text,
  'base_salary' : IDL.Float64,
  'joining_date' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'emp_id' : IDL.Nat,
  'department' : IDL.Text,
  'biometric_id' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'emp_name' : IDL.Text,
  'date' : IDL.Text,
  'emp_id' : IDL.Nat,
  'overtime_hours' : IDL.Float64,
  'attendance_id' : IDL.Nat,
  'check_out' : IDL.Opt(IDL.Text),
  'check_in' : IDL.Opt(IDL.Text),
  'total_hours' : IDL.Float64,
});
export const Attendance = IDL.Record({
  'status' : IDL.Text,
  'date' : IDL.Text,
  'emp_id' : IDL.Nat,
  'overtime_hours' : IDL.Float64,
  'attendance_id' : IDL.Nat,
  'check_out' : IDL.Opt(IDL.Text),
  'check_in' : IDL.Opt(IDL.Text),
  'total_hours' : IDL.Float64,
});
export const SalaryRecord = IDL.Record({
  'overtime_amount' : IDL.Float64,
  'processed_date' : IDL.Text,
  'net_salary' : IDL.Float64,
  'month_year' : IDL.Text,
  'emp_id' : IDL.Nat,
  'present_days' : IDL.Int,
  'salary_id' : IDL.Nat,
  'advance_deduction' : IDL.Float64,
  'absent_days' : IDL.Int,
  'basic_earned' : IDL.Float64,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const SalaryInput = IDL.Record({
  'overtime_amount' : IDL.Float64,
  'net_salary' : IDL.Float64,
  'month_year' : IDL.Text,
  'emp_id' : IDL.Nat,
  'present_days' : IDL.Int,
  'advance_deduction' : IDL.Float64,
  'absent_days' : IDL.Int,
  'basic_earned' : IDL.Float64,
});
export const UpdateEmployee = IDL.Record({
  'emp_code' : IDL.Text,
  'base_salary' : IDL.Float64,
  'joining_date' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'department' : IDL.Text,
  'biometric_id' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEmployee' : IDL.Func([NewEmployee], [Result_1], []),
  'approveAdvance' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'calculateSalary' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [Result_3],
      ['query'],
    ),
  'deleteEmployee' : IDL.Func([IDL.Nat], [Result], []),
  'getAdvanceRequests' : IDL.Func(
      [],
      [IDL.Vec(AdvanceRequestWithName)],
      ['query'],
    ),
  'getAdvanceRequestsByEmployee' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AdvanceRequest)],
      ['query'],
    ),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAttendance' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByEmployee' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
  'getEmployeeByBiometricId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Employee)],
      ['query'],
    ),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getSalaryRecord' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(SalaryRecord)],
      ['query'],
    ),
  'getSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
  'getTotalAdvanceDeduction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'markAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'processBiometricScan' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'processSalary' : IDL.Func([SalaryInput], [Result_1], []),
  'rejectAdvance' : IDL.Func([IDL.Nat], [Result], []),
  'submitAdvanceRequest' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Int, IDL.Text],
      [Result_1],
      [],
    ),
  'updateEmployee' : IDL.Func([IDL.Nat, UpdateEmployee], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewEmployee = IDL.Record({
    'emp_code' : IDL.Text,
    'base_salary' : IDL.Float64,
    'joining_date' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'department' : IDL.Text,
    'biometric_id' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const SalaryCalculation = IDL.Record({
    'emp_name' : IDL.Text,
    'overtime_amount' : IDL.Float64,
    'base_salary' : IDL.Float64,
    'days_in_month' : IDL.Int,
    'net_salary' : IDL.Float64,
    'total_overtime_hours' : IDL.Float64,
    'month_year' : IDL.Text,
    'emp_id' : IDL.Nat,
    'present_days' : IDL.Int,
    'advance_deduction' : IDL.Float64,
    'absent_days' : IDL.Int,
    'basic_earned' : IDL.Float64,
  });
  const Result_3 = IDL.Variant({ 'ok' : SalaryCalculation, 'err' : IDL.Text });
  const AdvanceRequestWithName = IDL.Record({
    'status' : IDL.Text,
    'emp_name' : IDL.Text,
    'total_repaid' : IDL.Float64,
    'approved_date' : IDL.Opt(IDL.Text),
    'emp_id' : IDL.Nat,
    'advance_id' : IDL.Nat,
    'repayment_months' : IDL.Int,
    'amount' : IDL.Float64,
    'reason' : IDL.Text,
    'monthly_deduction' : IDL.Float64,
    'request_date' : IDL.Text,
  });
  const AdvanceRequest = IDL.Record({
    'status' : IDL.Text,
    'total_repaid' : IDL.Float64,
    'approved_date' : IDL.Opt(IDL.Text),
    'emp_id' : IDL.Nat,
    'advance_id' : IDL.Nat,
    'repayment_months' : IDL.Int,
    'amount' : IDL.Float64,
    'reason' : IDL.Text,
    'monthly_deduction' : IDL.Float64,
    'request_date' : IDL.Text,
  });
  const Employee = IDL.Record({
    'emp_code' : IDL.Text,
    'status' : IDL.Text,
    'base_salary' : IDL.Float64,
    'joining_date' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'emp_id' : IDL.Nat,
    'department' : IDL.Text,
    'biometric_id' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'emp_name' : IDL.Text,
    'date' : IDL.Text,
    'emp_id' : IDL.Nat,
    'overtime_hours' : IDL.Float64,
    'attendance_id' : IDL.Nat,
    'check_out' : IDL.Opt(IDL.Text),
    'check_in' : IDL.Opt(IDL.Text),
    'total_hours' : IDL.Float64,
  });
  const Attendance = IDL.Record({
    'status' : IDL.Text,
    'date' : IDL.Text,
    'emp_id' : IDL.Nat,
    'overtime_hours' : IDL.Float64,
    'attendance_id' : IDL.Nat,
    'check_out' : IDL.Opt(IDL.Text),
    'check_in' : IDL.Opt(IDL.Text),
    'total_hours' : IDL.Float64,
  });
  const SalaryRecord = IDL.Record({
    'overtime_amount' : IDL.Float64,
    'processed_date' : IDL.Text,
    'net_salary' : IDL.Float64,
    'month_year' : IDL.Text,
    'emp_id' : IDL.Nat,
    'present_days' : IDL.Int,
    'salary_id' : IDL.Nat,
    'advance_deduction' : IDL.Float64,
    'absent_days' : IDL.Int,
    'basic_earned' : IDL.Float64,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const SalaryInput = IDL.Record({
    'overtime_amount' : IDL.Float64,
    'net_salary' : IDL.Float64,
    'month_year' : IDL.Text,
    'emp_id' : IDL.Nat,
    'present_days' : IDL.Int,
    'advance_deduction' : IDL.Float64,
    'absent_days' : IDL.Int,
    'basic_earned' : IDL.Float64,
  });
  const UpdateEmployee = IDL.Record({
    'emp_code' : IDL.Text,
    'base_salary' : IDL.Float64,
    'joining_date' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'department' : IDL.Text,
    'biometric_id' : IDL.Text,
  });
  
  return IDL.Service({
    'addEmployee' : IDL.Func([NewEmployee], [Result_1], []),
    'approveAdvance' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'calculateSalary' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [Result_3],
        ['query'],
      ),
    'deleteEmployee' : IDL.Func([IDL.Nat], [Result], []),
    'getAdvanceRequests' : IDL.Func(
        [],
        [IDL.Vec(AdvanceRequestWithName)],
        ['query'],
      ),
    'getAdvanceRequestsByEmployee' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AdvanceRequest)],
        ['query'],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAttendance' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByEmployee' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
    'getEmployeeByBiometricId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Employee)],
        ['query'],
      ),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getSalaryRecord' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(SalaryRecord)],
        ['query'],
      ),
    'getSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
    'getTotalAdvanceDeduction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'markAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'processBiometricScan' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'processSalary' : IDL.Func([SalaryInput], [Result_1], []),
    'rejectAdvance' : IDL.Func([IDL.Nat], [Result], []),
    'submitAdvanceRequest' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Int, IDL.Text],
        [Result_1],
        [],
      ),
    'updateEmployee' : IDL.Func([IDL.Nat, UpdateEmployee], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };